# this is automatically generated by running $ rails g migration AddDirectorToMovie director:string
# referenced a tutorial : https://gist.github.com/yokolet/2176753

class AddDirectorToMovie < ActiveRecord::Migration
  def change
    add_column :movies, :director, :string
  end
end
